; bed.g
; called to level the bed
;
; generated by RepRapFirmware Configuration Tool v3.5.0-rc.4+1 on Sat Apr 13 2024 08:26:03 GMT-0400 (Eastern Daylight Time)

G29 ; call mesh bed compensation
